apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: App1
  replicas: 4 # tells deployment to run 4 pods matching the template
  template:
    metadata:
      labels:
        app: App1
    spec:
      containers:
      - name: Container1
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          limits:
          requests: 
      - name: Container2
        image: nginx:latest
        ports:
        - containerPort: 80
